server:
  port: 8189
  servlet:
    context-path: /freshcafe

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  application:
    name: freshcafe
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
  redis:
    host: ${REDISHOST}
    port: ${REDISPORT}
    password: ${REDISPASSWORD}
    username: ${REDISUSER}
    url: ${REDIS_URL}

utils:
  cart:
    prefix: FRESHCAFE_CART_

